
var Country_Global_ABC = 'http://feeds.abcnews.com/abcnews/internationalheadlines';
var Industry_Technology_Y_Combinator = 'https://news.ycombinator.com/rss';

var industries = [
    {'title': 'SKIP THIS STEP                   ', 'feeds': []},//Don't put anything here, this is the users exit strategy in case (s)he doesn't want to chose anything
    {'title': 'Pets                             ', 'feeds': ['http://kb.rspca.org.au/rss.php?c=98', 'http://kb.rspca.org.au/rss.php?c=4']},
    {'title': 'Agriculture                      ', 'feeds': ['http://www.reddit.com/r/Agriculture/.rss']},
    {'title': 'Beverage & Tobacco               ', 'feeds': ['http://www.reddit.com/r/alcohol/.rss']},
    {'title': 'Accounting                       ', 'feeds': ['http://www.reddit.com/r/Accounting/.rss']},
    {'title': 'Advertising                      ', 'feeds': ['http://www.reddit.com/r/advertising/.rss']},
    {'title': 'Aerospace                        ', 'feeds': ['http://www.reddit.com/r/aerospace/.rss']},
    {'title': 'Aircraft                         ', 'feeds': ['http://www.reddit.com/r/aviation/.rss']},
    {'title': 'Airline                          ', 'feeds': ['http://www.reddit.com/r/aviation/.rss']},
//    {'title': 'Apparel & Accessories            ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Architecture                     ', 'feeds': ['http://www.reddit.com/r/architecture/.rss']},
    {'title': 'Automotive                       ', 'feeds': ['http://www.reddit.com/r/automotive/.rss']},
    {'title': 'Banking                          ', 'feeds': ['http://www.reddit.com/r/Banking/.rss']},
//    {'title': 'Broadcasting                     ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Brokerage                        ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Biotechnology                    ', 'feeds': ['http://www.reddit.com/r/biotechnology/.rss','http://www.cell.com/rssFeed/biotechnology/rss.mostread.xml']},
//    {'title': 'Chemical                         ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Consumer Products                ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Cosmetics                        ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Defense                          ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Design                           ', 'feeds': ['http://www.reddit.com/r/Design/.rss']},
//    {'title': 'Department Stores                ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Software                         ', 'feeds': ['http://www.reddit.com/r/software/.rss']},
    {'title': 'Education                        ', 'feeds': ['http://www.reddit.com/r/Teachers/.rss', 'http://www.reddit.com/r/education/.rss']},
    {'title': 'Sports                           ', 'feeds': ['http://www.reddit.com/r/sports/.rss']},
    {'title': 'Electronics                      ', 'feeds': ['http://www.reddit.com/r/.rss']},
    {'title': 'Energy                           ', 'feeds': ['http://www.reddit.com/r/energy/.rss']},
    {'title': 'Entertainment & Leisure          ', 'feeds': ['http://www.reddit.com/r/entertainment/.rss']},
    {'title': 'Television                       ', 'feeds': ['http://www.reddit.com/r/television/.rss']},
//    {'title': 'Executive Search                 ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Financial Services               ', 'feeds': ['http://www.reddit.com/r/finance/.rss','http://www.reddit.com/r/FinancialCareers/.rss']},
    {'title': 'Food                             ', 'feeds': ['http://www.food.com/rss?']},
    {'title': 'Health Care                      ', 'feeds': ['http://www.reddit.com/r/food/.rss']},
//    {'title': 'Internet Publishing              ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Investment Banking               ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Legal                            ', 'feeds': ['http://www.reddit.com/r/investing/.rss']},
    {'title': 'Manufacturing                    ', 'feeds': ['http://www.reddit.com/r/manufacturing/.rss']},
    {'title': 'Motion Picture & Video           ', 'feeds': ['http://www.reddit.com/r/movies/.rss']},
    {'title': 'Music                            ', 'feeds': ['http://www.rollingstone.com/siteServices/rss/songReviews']},
    {'title': 'Newspaper Publishers             ', 'feeds': ['http://www.reddit.com/r/newspapers/.rss', 'http://www.reddit.com/r/publishing/.rss']},
    {'title': 'Publishing                       ', 'feeds': ['http://www.reddit.com/r/publishing/.rss']},
    {'title': 'Real Estate                      ', 'feeds': ['http://www.reddit.com/r/RealEstate/.rss']},
//    {'title': 'Retail & Wholesale               ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Securities & Commodity Exchanges ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Service                          ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Soap & Detergent                 ', 'feeds': [Industry_Technology_Y_Combinator]},
    {'title': 'Technology                       ', 'feeds': ['http://www.reddit.com/r/technology/.rss']},
//    {'title': 'Telecommunications               ', 'feeds': ['Industry_Technology_Y_Combinator']},
    {'title': 'Transportation                   ', 'feeds': ['http://www.reddit.com/r/Transportation/.rss']},
//    {'title': 'Venture Capital                  ', 'feeds': [Industry_Technology_Y_Combinator]},
//    {'title': 'Other Industries                 ', 'feeds': [Industry_Technology_Y_Combinator]}
];

